# Actions名称

name: Docker Image CI

# 执行时机
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: checkout
        uses: actions/checkout@master

      # Runs a set of commands using the runners shell
      - name: install
        run: npm install

      - name: build project
        run: npm run build

      - name: Build the Docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -t zhihu:latest .
          docker tag zhihu registry.cn-hangzhou.aliyuncs.com/xuech/zhihu:latest
          docker push registry.cn-hangzhou.aliyuncs.com/xuech/zhihu:latest
      - name: ssh docker login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd ~ && sh zhihu-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
